from app.services.model_training import load_data
from app.services.model_training import train_stacked_classifier
from app.services.prediction_utils import _load_model_and_vectorizer
from app.services.prediction_utils import predict_job_category
from app.services.resume_parser import process_resume
from app.services.resume_parser import preprocess_text
from app.services.resume_parser import process_resumes