from app.services.model_training import load_data
from app.services.model_training import train_stacked_classifier
from app.services.prediction_utils import load_model_and_vectorizer
from app.services.prediction_utils import predict_job_category